### ISSUE TITLE
$strict-normalize doesn't seem to work as intended

### ISSUE THREAD

**Issue by bhrutledge** [JohnAlbin/normalize-scss#33]
It's almost always used liked this:

```
@if not $strict-normalize or support-legacy-browser(ie, "7") {
  // Vertical rhythm code...
}
```

Since `support-legacy-browser` returns `true`, the vertical rhythm code gets included. I'm not sure what the expected behavior is, but the result is `$strict-normalize` is essentially ignored.

**Comment by JohnAlbin** [comment]
`support-legacy-browser(ie, "7")` only returns true if you leave Compass' settings as the default. Since compass includes IE7 support due to its current usages statistics.

normalize-scss assumes that if you want IE7 support than that is more important than your request for $strict-normalize.

If you change the defaults so that IE7 is not supported, then the $strict-normalize will control the output as expected.
