### ISSUE TITLE
Publish normalize-scss 3.0.3 to npm

### ISSUE THREAD

**Issue by JohnAlbin** [JohnAlbin/normalize-scss#40]
Hey, Martin! @apparentlymart

Thanks for publishing normalize-scss to npm for me, but I can't publish the latest release to npmjs.org.

```
$ npm publish normalize-scss
npm ERR! publish Failed PUT 403

npm ERR! You do not have permission to publish 'normalize-scss'. Are you logged in as the correct user? : normalize-scss
```

Can you add me as having permissions to publish to that namespace so I can publish 3.0.3?

`npm owner add johnalbin normalize-scss`

**Comment by apparentlymart** [comment]
Hi John,

I don't really remember doing this so I expect I was trying to accomplish something else at the time and this was a mistake. However, I have now added you... and once you confirm you have access by all means drop me or let me know and I will drop myself from it, since I have no business being an owner of this project on npm.

**Comment by JohnAlbin** [comment]
Thanks, @apparentlymart!
