### ISSUE TITLE
normalize folder in beta release (4.0.0-beta.1) missing

### ISSUE THREAD

**Issue by strarsis** [JohnAlbin/normalize-scss#42]
_normalize.scss imports files from the normalize folder which is missing 
in the package for beta release 4.0.0-beta.1.

Error at first import in file:
````
[...]
File to import not found
or unreadable: normalize/variables.
[...]
````
...or with libsass:
````
[...]
Error: Could not import `normalize/variables` from any of the following locations
[...]
````

Thank you and
With best regards

**Comment by JohnAlbin** [comment]
Yep, this is caused by the `files` key in package.json. Which isn't required and, as far as I can tell, is just there to make you make stupid, fatal errors like the one you described. https://github.com/JohnAlbin/normalize-scss/blob/030ba7658a267b3e75b2b996bfd339ea9d96073f/package.json#L23-L25

I've already removed `files` from package.json and released 4.0.0.
